# Generated by Django 5.0.4 on 2024-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthPlus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$j09GQYiryMjGvcyqQhYlPX$8e/2f02RUV3PovlwaAIODTK5TLA5jEx6lwlPHTxUxyk=', max_length=128),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$IKvSqdfcaFjGZiZvRkCg2u$zfOciyg5muX08mIxBRAxu9fcyDaik31+fhYk7pCNqU0=', max_length=128),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('patients', models.ManyToManyField(related_name='diseases', to='HealthPlus.patient')),
            ],
        ),
    ]
