# Generated by Django 5.0.4 on 2024-05-28 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthPlus', '0003_alter_doctor_password_alter_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='diseases',
            field=models.ManyToManyField(related_name='doctors', to='HealthPlus.disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.ManyToManyField(related_name='patients', to='HealthPlus.disease'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$5ebfEYKv1LEG817pc2l8KZ$w4MBU1SsceTD2Tgej8+6Z76jTi8k5+1+/67az3k5Bv4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$sQJGmUQCdP0ruc73Rb4ATM$K9edszpKApL++B2pcxAGZ3TGO3kmrQutILXv9HnP+fs=', max_length=128),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('current', 'Current'), ('past', 'Past'), ('upcoming', 'Upcoming')], max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='HealthPlus.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='HealthPlus.patient')),
            ],
        ),
    ]
