# Generated by Django 5.0.4 on 2024-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthPlus', '0004_remove_disease_patients_doctor_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$PhnuiEDlq1Q6larWSLMjPz$PKMkLqXuqk5EmaF0sc5q8BQrGI06XffYUOhW4PrAoSY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Oy3sNhL9C6eXZ6eFBq0PjL$JCsAmqW9iZ/HcUfbIMFX9sIM9E/QdKfNcFONcKLkDio=', max_length=128),
        ),
    ]
