# Generated by Django 5.0.4 on 2024-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthPlus', '0006_alter_doctor_password_alter_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$F45fNmzKzJWKzleYqmZMI3$5TREL9lXcqd3wwFZ0WdVO8GeiaQP1AnxU99hjXeYhZg=', max_length=128),
        ),
    ]
