# Generated by Django 5.0.4 on 2024-05-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthPlus', '0009_remove_doctor_email_remove_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('current', 'Current'), ('past', 'Past'), ('upcoming', 'Upcoming')], default='pending', max_length=50),
        ),
    ]
