# Generated by Django 5.0.4 on 2024-06-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthPlus', '0012_remove_shift_doctor_alter_appointment_status_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
